//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityManage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class njEntities : DbContext
    {
        public njEntities()
            : base("name=njEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category_show_view> category_show_view { get; set; }
        public DbSet<vedio_show_view> vedio_show_view { get; set; }
        public DbSet<T_OPT_STNET_CONTENT> T_OPT_STNET_CONTENT { get; set; }
        public DbSet<T_INFO_STNET_CATEGORY> T_INFO_STNET_CATEGORY { get; set; }
        public DbSet<SYS_USER> SYS_USER { get; set; }
        public DbSet<T_OPT_STNET_CUT> T_OPT_STNET_CUT { get; set; }
        public DbSet<T_OPT_STNET_EXCHANGE> T_OPT_STNET_EXCHANGE { get; set; }
        public DbSet<T_OPT_STNET_NATION> T_OPT_STNET_NATION { get; set; }
    }
}
