//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityManage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class njEntities : DbContext
    {
        public njEntities()
            : base("name=njEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<t_opt_stnet_exchange> t_opt_stnet_exchange { get; set; }
        public DbSet<t_opt_stnet_content> t_opt_stnet_content { get; set; }
        public DbSet<category_show_view> category_show_view { get; set; }
        public DbSet<t_opt_stnet_cut> t_opt_stnet_cut { get; set; }
        public DbSet<t_info_stnet_category> t_info_stnet_category { get; set; }
        public DbSet<t_opt_stnet_nation> t_opt_stnet_nation { get; set; }
        public DbSet<sys_user> sys_user { get; set; }
        public DbSet<vedio_show_view> vedio_show_view { get; set; }
    }
}
