//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INFO_STNET_CATEGORY
    {
        public string CATEGORY_ID { get; set; }
        public string TITLE { get; set; }
        public string PID { get; set; }
        public string DESP { get; set; }
        public string IMGURL { get; set; }
        public string CREATEDATE { get; set; }
        public string CREATEUSER { get; set; }
        public string DELESTATE { get; set; }
        public string OUTERURL { get; set; }
        public string INNERURL { get; set; }
    }
}
