//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OPT_STNET_CUT
    {
        public string id { get; set; }
        public string pid { get; set; }
        public string name { get; set; }
        public string path { get; set; }
        public string module { get; set; }
    }
}
