//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OPT_STNET_NATION
    {
        public long id { get; set; }
        public string code { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public Nullable<long> parent_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string district { get; set; }
        public System.DateTime last_update_time { get; set; }
        public Nullable<long> @operator { get; set; }
        public string operator_ip { get; set; }
    }
}
