//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_opt_stnet_exchange
    {
        public string ID { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public string CREATEDATE { get; set; }
        public Nullable<int> STATE { get; set; }
        public string PID { get; set; }
        public string CREATEUSER { get; set; }
        public string INDUSTRY { get; set; }
        public string PROVINCE { get; set; }
        public string CITY { get; set; }
        public string DISTRICT { get; set; }
        public string PCD { get; set; }
    }
}
